site_name: DAB Radio V2.0
site_url: https://example.com/
theme:
  name: readthedocs
  
markdown_extensions:
  - admonition
nav:
    - Home: index.md
    - Hard- und Software Konfiguration: Hard- und Software Knfiguration.markdown
    - Installation der Entwicklungsumgebung: Installation der Entwicklungsumgebung.markdown
    - Testsoftware: Testsoftware.markdown
    - Quellen: Quellen.markdown
    - Datenblätter: Datenblätter.markdown