DAB_2_V0.1.ino
BUFFER_MULTIPLIER
LVGL buffer multiplier.
< Light and versatile Embedded Graphics Library (LVGL) < General TFT library (TFT_eSPI) < Communication header for the touch controller - between "FT6206" and LVGL Arduino I2C library < LED driver library (PCA9634) Port expander library (MPC23017) < Bluetooth Module library (BM83/BM64) < SoftwareSerial Library for ESP32 < Sound processor library (BD37544FS) Encoder library for ESP32
RX_PIN
BM83 UART RX.
TX_PIN
BM83 UART TX.
TX_IND
BM83 TX IND.
DAC1
DAC pin for DC_SET_V.
ENC1_ROTARY_PIN_A
Encoder 1 Pin A.
ENC1_ROTARY_PIN_B
Encoder 1 Pin B.
ENC2_ROTARY_PIN_A
Encoder 2 Pin A.
ENC2_ROTARY_PIN_B
Encoder 2 Pin B.
CLICKS_PER_STEP
MIN_POS
Max volume 0 dB.
MAX_POS
Min volume -87 dB.
START_POS
Volume start position.
INCREMENT
Volume increment.
const int mfbPin
BM83 MFB Pin, required for BM83 power on.
Referenced by event_bm83setup, setup.
lv_group_t* g
An object group.
Referenced by setup.
lv_indev_t* encoder_indev
Encoder 1 LVGL input device.
Referenced by setup.
uint8_t conf
Referenced by loop_task, read_inputs.
int i
Referenced by read_inputs.
int vol
Current volume value.
int encoderLastValue
Referenced by enc_get_new_moves.
int k
Current encoder position (volume)
Referenced by rotate_u.
int menu_status
int current_tab
Referenced by button_event_handler, menu_bar.
int prev_tab
Referenced by button_event_handler, encoder_read.
int home_tab
Referenced by encoder_read.
TaskHandle_t Task1
Taskhandle for "read_inputs" task.
Referenced by setup.
TaskHandle_t Task2
Referenced by setup.
TaskHandle_t Task3
Referenced by setup.
TaskHandle_t Task4
Taskhandle for "read_inputs" task.
TaskHandle_t Task5
TaskHandle_t Task6
lv_obj_t* splash_screen
lv_obj_t* audio_page
Referenced by setup.
lv_obj_t* bt_page
Referenced by setup.
lv_obj_t* power_page
Referenced by setup.
lv_obj_t* menu_screen
lv_obj_t* menu_container
lv_obj_t* music_control_container
Referenced by menu_bar, setup.
lv_obj_t* status_bar_container
Referenced by setup.
lv_obj_t* audio_control_container
Referenced by setup.
lv_obj_t* menu_control_container
Referenced by menu_bar, setup.
lv_obj_t* bt_control_container
Referenced by setup.
lv_obj_t* power_control_container
Referenced by setup.
lv_obj_t* tabview
Referenced by button_event_handler, encoder_read, event_handler, menu_bar, setup.
lv_obj_t* tab_home
Referenced by setup.
lv_obj_t* tab_vis
Referenced by setup.
lv_obj_t* tab_bt
Referenced by setup.
lv_obj_t* tab_aux
Referenced by setup.
lv_obj_t* tab_dab
Referenced by setup.
lv_obj_t* tab_menu
Referenced by setup.
lv_obj_t* tab_bt_settings
Referenced by setup.
lv_obj_t* tab_audio_settings
Referenced by setup.
lv_obj_t* tab_power_settings
Referenced by setup.
lv_obj_t* tab_display_settings
Referenced by setup.
lv_obj_t* tab_led_settings
Referenced by setup.
lv_obj_t* btn_play
Referenced by setup.
lv_obj_t* btn_next
Referenced by setup.
lv_obj_t* btn_prev
Referenced by setup.
lv_obj_t* btn_mute
Referenced by setup.
lv_obj_t* btn_back
Referenced by button_event_handler, setup.
lv_obj_t* btn_minus
Referenced by button_event_handler, setup.
lv_obj_t* btn_plus
Referenced by button_event_handler, setup.
lv_obj_t* btn_forw
Referenced by button_event_handler, setup.
lv_obj_t* list1
Referenced by setup.
lv_obj_t* list_btn_bt
Referenced by event_handler, setup.
lv_obj_t* list_btn_audio
Referenced by event_handler, setup.
lv_obj_t* list_btn_disp
Referenced by event_handler, setup.
lv_obj_t* list_btn_leds
Referenced by event_handler, setup.
lv_obj_t* list_btn_misc
Referenced by event_handler, setup.
lv_obj_t* list_btn_pwr
Referenced by event_handler, setup.
lv_obj_t* btn1
Referenced by setup.
lv_obj_t* btn2
Referenced by setup.
lv_obj_t* btn3
Referenced by setup.
lv_obj_t* btn_standby
Referenced by setup.
lv_obj_t* btn_pwrup
Referenced by setup.
lv_obj_t* btn_pwrdwn
Referenced by setup.
lv_obj_t* btn_analog_on
Referenced by setup.
lv_obj_t* btn_poweramp_on
Referenced by setup.
lv_obj_t* sw1
Referenced by event_sw1, setup.
lv_obj_t* sw2
Referenced by event_sw2, setup.
lv_obj_t* sw3
Referenced by event_sw3, setup.
lv_obj_t* label
Referenced by setup.
lv_obj_t* label_battery
Referenced by setup.
lv_obj_t* label_bluetooth
Referenced by setup.
lv_obj_t* label_clock
Referenced by setup.
lv_obj_t* slider_ingain
Referenced by setup, slider_event_cb_ingain.
lv_obj_t* slider_bass
Referenced by setup, slider_event_cb_bass.
lv_obj_t* slider_mid
Referenced by setup, slider_event_cb_mid.
lv_obj_t* slider_treb
Referenced by setup, slider_event_cb_treb.
lv_obj_t* slider_label_ingain
Referenced by setup, slider_event_cb_ingain.
lv_obj_t* slider_label_bass
Referenced by setup, slider_event_cb_bass.
lv_obj_t* slider_label_mid
Referenced by setup, slider_event_cb_mid.
lv_obj_t* slider_label_treb
Referenced by setup, slider_event_cb_treb.
lv_obj_t* info_ingain
Referenced by setup.
lv_obj_t* info_bass
Referenced by setup.
lv_obj_t* info_mid
Referenced by setup.
lv_obj_t* info_treb
Referenced by setup.
lv_disp_buf_t disp_buf
Referenced by setup.
lv_color_t buf_1[LV_HOR_RES_MAX *BUFFER_MULTIPLIER][LV_HOR_RES_MAX *BUFFER_MULTIPLIER]
LVGL display buffer.
Referenced by setup.
lv_color_t buf_2[LV_HOR_RES_MAX *BUFFER_MULTIPLIER][LV_HOR_RES_MAX *BUFFER_MULTIPLIER]
LVGL display buffer.
Referenced by setup.
ESPRotary r
Encoder 1 instance.
Referenced by enc_get_new_moves, loop_task, setup.
ESPRotary u
Encoder 2 instance.
Referenced by loop_task, rotate_u, setup.
BD37544FS bd
Sound processor instance (BD37544FS)
Referenced by event_analog_on, event_pwrdown, event_pwrup, event_soundsetup, rotate_u, slider_event_cb_bass, slider_event_cb_ingain, slider_event_cb_mid, slider_event_cb_treb.
MCP23017 mcp1
MCP1 instance (Display board)
Referenced by encoder_read, loop_task, setup.
MCP23017 mcp2
MCP2 instance (MCU board)
Referenced by event_analog_on, event_poweramp_on, event_pwrdown, event_pwrup, event_standby, event_sw1, event_sw2, event_sw3, setup.
TFT_eSPI tft
TFT instance.
Referenced by my_disp_flush, setup.
LV_IMG_DECLARE(raulogo)
SoftwareSerial swSerial(RX_PIN, TX_PIN)
Software serial instance (BM83)
Referenced by setup.
BM83 bm83(swSerial, TX_IND)
BM83 instance (BM83)
Referenced by event_bm83pair, event_bm83setup, read_inputs.
PCA9634 ledDriver(0x15, NULL)
Led driver instance (PCA9634)
Referenced by setup.
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
LVGL display flushing
Flush the display with the given color. The lv_disp_flush_ready() function is called after the display has been flushed disp The display driver to use. area The area of the display to be flushed. color_p A pointer to a color structure.
References tft.
Referenced by setup.
void setup()
References audio_control_container, audio_page, bt_control_container, bt_page, btn1, btn2, btn3, btn_analog_on, btn_back, btn_forw, btn_minus, btn_mute, btn_next, btn_play, btn_plus, btn_poweramp_on, btn_prev, btn_pwrdwn, btn_pwrup, btn_standby, buf_1, buf_2, button_event_handler, CLICKS_PER_STEP, disp_buf, ENC1_ROTARY_PIN_A, ENC1_ROTARY_PIN_B, ENC2_ROTARY_PIN_A, ENC2_ROTARY_PIN_B, encoder_indev, encoder_read, event_analog_on, event_bm83pair, event_bm83setup, event_handler, event_poweramp_on, event_pwrdown, event_pwrup, event_soundsetup, event_standby, event_sw1, event_sw2, event_sw3, g, INCREMENT, info_bass, info_ingain, info_mid, info_treb, label, label_battery, label_bluetooth, label_clock, ledDriver, list1, list_btn_audio, list_btn_bt, list_btn_disp, list_btn_leds, list_btn_misc, list_btn_pwr, loop_task, MAX_POS, mcp1, mcp2, menu_bar, menu_control_container, mfbPin, MIN_POS, music_control_container, my_disp_flush, my_touchpad_read, power_control_container, power_page, r, read_inputs, rotate_r, rotate_u, showDirection_r, showDirection_u, slider_bass, slider_event_cb_bass, slider_event_cb_ingain, slider_event_cb_mid, slider_event_cb_treb, slider_ingain, slider_label_bass, slider_label_ingain, slider_label_mid, slider_label_treb, slider_mid, slider_treb, START_POS, status_bar_container, sw1, sw2, sw3, swSerial, tab_audio_settings, tab_aux, tab_bt, tab_bt_settings, tab_dab, tab_display_settings, tab_home, tab_led_settings, tab_menu, tab_power_settings, tab_vis, tabview, Task1, Task2, Task3, tft, touch, u.
void loop()
void loop_task(void *pvParameters)
References conf, mcp1, r, u.
Referenced by setup.
void read_inputs(void *pvParameters)
Reads the music control buttons and sets the corresponding bits in the configuration register to send the according command to the BM83 module pvParameters The parameter is a pointer to the task handle.
References bm83, conf, i.
Referenced by setup.
static void button_event_handler(lv_obj_t *obj, lv_event_t event)
When the user clicks on the back button, the previous tab is activated obj The object that received the event. event The event that triggered the callback.
References btn_back, btn_forw, btn_minus, btn_plus, current_tab, prev_tab, tabview.
Referenced by setup.
static void event_handler(lv_obj_t *obj, lv_event_t event)
When the user clicks on a button, the tab view is set to the corresponding tab obj The object that received the event. event The event that happened.
References list_btn_audio, list_btn_bt, list_btn_disp, list_btn_leds, list_btn_misc, list_btn_pwr, tabview.
Referenced by setup.
static void event_standby(lv_obj_t *btn_standby, lv_event_t event)
* Standby Mode: When the Standby button is pressed, the 7.5V, +-5V, PVCC, and Power Amp shutdown activation pins are set to low, and the Power Amp mute activation pin is set to high btn_standby The button object that we want to attach the event to. event The event that triggered the callback.
References mcp2.
Referenced by setup.
static void event_pwrup(lv_obj_t *btn_pwrup, lv_event_t event)
Power down process: Set the power down pin to low. Set the power amp shutdown pin to low. Set the +-5V pin to high. Set the PVCC pin to high. Sets GPIO26 to ~3.1 V Set the +-5V pin to high. Set the 7.5V pin to high. Set the sound processor pins to the default values. Set the power down pin to low Set the power amp mute pin to low. btn_pwrup The button object that we created in the previous step. event The event that triggered the callback.
References bd, DAC1, mcp2.
Referenced by setup.
static void event_pwrdown(lv_obj_t *btn_pwrdwn, lv_event_t event)
Power down process: Set the power down pin to high. Set the power amp mute pin to high. Set the power amp shutdown pin to high. Set the +-5V pin to low. Set the PVCC pin to low. Set the DAC1 pin to 0. Set the +-5V pin to low. Set the 7.5V pin to low. Set the sound processor pins to the default values. Set the power down pin to low btn_pwrdwn The button object that we created in the previous step. event The event that triggered the callback.
References bd, DAC1, mcp2.
Referenced by setup.
static void event_analog_on(lv_obj_t *btn_analog_on, lv_event_t event)
Set the sound processor to the default settings btn_analog_on The button object that we created earlier. event The event that triggered the callback.
References bd, mcp2.
Referenced by setup.
static void event_poweramp_on(lv_obj_t *btn_poweramp_on, lv_event_t event)
The function is called when the user clicks on the "Power amp on" button. The function sets GPIO26 to ~3.1 V, which is the voltage that the power amp needs to turn on. The function also enables the power amp by setting the PVCC pin to high. The function also deactivates the power amp shutdown by setting the shutdown pin to low. The function also deactivates the power amp mute by setting the mute pin to low. The function also deactivates the sound processor mute by setting the mute pin to low. The function ends by printing a message to the serial monitor. btn_poweramp_on The button object that we want to attach the event to. event The event that triggered the callback.
References DAC1, mcp2.
Referenced by setup.
static void event_bm83setup(lv_obj_t *btn1, lv_event_t event)
When the BM83 button is pressed, the MFB pin is set to "High" to power on the BM83. The BM83 is then powered on by sending the "power on" command over UART. The MFB pin is then set to "Low". Setting the pin "High" is only required everytime the BM83 Module has to be setup again. btn1 The button object that was clicked. event The event that triggered the callback.
References bm83, mfbPin.
Referenced by setup.
static void event_bm83pair(lv_obj_t *btn2, lv_event_t event)
When the user clicks on the "Pair" button, the MMI action "Entering Pairing" is sent to the BM83 btn2 The button that was clicked. event The event that triggered the callback.
References bm83.
Referenced by setup.
static void event_soundsetup(lv_obj_t *btn3, lv_event_t event)
Set the sound setup to the default values btn3 the button that was pressed event
References bd.
Referenced by setup.
static void event_sw1(lv_obj_t *sw1, lv_event_t event_sw1)
References event_sw1, mcp2, sw1.
Referenced by event_sw1, setup.
static void event_sw2(lv_obj_t *sw2, lv_event_t event)
When the state of the switch changes, print out the state of the switch and set the state of the according MCP23017 pin sw2 The switch object event The event that triggered the callback.
References mcp2, sw2.
Referenced by setup.
static void event_sw3(lv_obj_t *sw3, lv_event_t event)
References mcp2, sw3.
Referenced by setup.
void rotate_r(ESPRotary &r)
Referenced by setup.
void showDirection_r(ESPRotary &r)
Referenced by setup.
void rotate_u(ESPRotary &u)
Rotate the rotary encoder and set the volume accordingly u
References bd, k, u.
Referenced by setup.
void showDirection_u(ESPRotary &u)
Referenced by setup.
bool encoder_read(lv_indev_drv_t *encoder_indev, lv_indev_data_t *data)
When the encoder is turned, it will send a signal to the microcontroller. The microcontroller will then read the signal and determine if the encoder has been turned. If it has, it will send a signal to the microcontroller that will be read by the encoder_read function. The encoder_read function will then determine if the encoder has been turned. encoder_indev The pointer to the encoder object. data The data object that is passed to the function. Nothing.
References enc_get_new_moves, home_tab, mcp1, prev_tab, tabview.
Referenced by setup.
int enc_get_new_moves()
Get the current encoder count and the difference between the current count and the last count The difference between the current encoder count and the previous encoder count.
References encoderLastValue, r.
Referenced by encoder_read.
void menu_bar(void *pvParameters)
When the user switches to the music tab, the music control container is moved to the foreground and the menu control container is moved to the background. When the user switches to the menu tab, the menu control container is moved to the foreground and the music control container is moved to the background pvParameters The parameter is a pointer to the task handle.
References current_tab, menu_control_container, music_control_container, tabview.
Referenced by setup.
static void slider_event_cb_ingain(lv_obj_t *slider_ingain, lv_event_t event)
When the slider is moved, the slider value is read and the slider label is updated. The slider value is then used to set the input gain slider_ingain the slider object event The event that triggered the callback.
References bd, slider_ingain, slider_label_ingain.
Referenced by setup.
static void slider_event_cb_bass(lv_obj_t *slider_bass, lv_event_t event)
When the slider value changes, update the label text and set the bass value slider_bass the slider object event The event that triggered the callback.
References bd, slider_bass, slider_label_bass.
Referenced by setup.
static void slider_event_cb_mid(lv_obj_t *slider_mid, lv_event_t event)
When the slider value changes, update the label text and set the middle value slider_mid The slider object. event The event that triggered the callback.
References bd, slider_label_mid, slider_mid.
Referenced by setup.
static void slider_event_cb_treb(lv_obj_t *slider_treb, lv_event_t event)
When the slider value changes, update the label text and set the treble value slider_treb the slider object event The type of event that occurred.
References bd, slider_label_treb, slider_treb.
Referenced by setup.